name: Build and deploy ASP.Net Core app to Azure Web App - BadgrBadges

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.1.515'
          include-prerelease: true

      - name: Restore NuGet packages
        run: dotnet restore Source/Microsoft.Teams.App.Badges/Microsoft.Teams.App.Badges.csproj

      - name: Build with dotnet
        run: dotnet build --configuration Release Source/Microsoft.Teams.App.Badges/Microsoft.Teams.App.Badges.csproj
